### ISSUE TITLE
I tried to connect using the example but I can not connect using postingkey.

### ISSUE THREAD

**Issue by landlove** [steemit/sc2-angular#4]
Hello
I want to use steemconnect2.
I tried to connect using the example but I can not connect using postingkey.
Only the active key or master key is used to connect.
Is this problem intended?
Or I want to know if I am doing wrong.

**Comment by bonustrack** [comment]
With SteemConnect2 you need to grant @busy.app permission to post on your behalf, so the app busy can post for you. This operation require at least your active key when you authorize the app then you can login with you memo key or posting key. You can revoke @busy.app anytime using this link http://v2.steemconnect.com/revoke/@busy.app
The active key is only used to make the operation in your browser then discarded, nothing stay or goes to the server.
